#!/bin/bash


## help option
if [[ $1 == "help" ]]; then
  echo "  $ mygit config"
  echo "  $ mygit init   <directory> <repo_name> <user>"
  echo "  $ mygit clone  <directory> <repo_name> <user>"
  echo "  $ mygit pull   <directory> <repo_name>"
  echo "  $ mygit commit <directory> <repo_name> <message>"
  exit 0
fi


## config option
if [[ $1 == "config" ]]; then
  if [ "$#" -ne 2 ]; then
    echo "format: mygit config <password>"
    exit 1
  fi

  git config --global user.email "sofia10102421@gmail.com"
  git config --global user.name "Sophiko Kvantaliani"
  git config --global user.password "$2"
  exit 0
fi


## clone option
if [[ $1 == "clone" ]]; then
  ## target directory
  repodir=$HOME/"$2""$3"/

  echo "Cloning repo..."
  git clone ssh://git@bitbucket.org/"$4"/"$3".git "$repodir"

  exit 0
fi


## init option
if [[ $1 == "init" ]]; then
  if [ "$#" -ne 4 ]; then
    echo "format: mygit init <directory> <repo_name> <user_name>"
    exit 1
  fi

  ## change to repo directory
  currentdir=$(pwd)
  repodir=$HOME/"$2""$3"/
  echo $repodir
  if [ ! -d "$repodir" ]; then
    mkdir "$repodir"
  fi
  cd "$repodir"

  echo "Initializing repo..."
  git init
  git remote add origin git@bitbucket.org:"$4"/"$3".git

  ## back to current directory
  cd $currentdir
  exit 0
fi

## init option
if [[ $1 == "pull" ]]; then
  if [ "$#" -ne 3 ]; then
    echo "format: mygit pull <directory> <repo_name>"
    exit 1
  fi

  ## change to repo directory
  currentdir=$(pwd)
  repodir=$HOME/"$2""$3"/
  echo $repodir
  cd "$repodir"

  echo "Pulling repo..."
  git pull

  ## back to current directory
  cd $currentdir
  exit 0
fi

## commit option
if [[ $1 == "commit" ]]; then
  if [ "$#" -ne 4 ]; then
    echo "format: mygit commit <directory> <repo_name> <message>"
    cd $currentdir
    exit 1
  fi

  ## change to repo directory
  currentdir=$(pwd)
  echo "$HOME/$2$3"
  cd $HOME/$2$3

  echo "Committing..."
  ## commit and push
  git add .
  git commit -m "$4"
  git push

  ## back to current directory
  cd $currentdir
  exit 0
fi

echo "Wrong command, try"
mygit help
exit 1
